version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    env_file: .env
    restart: always
    networks:
      - local
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USERNAME}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  book-store:
    build:
      context: .
      target: builder
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local
    volumes:
      - ./src:/app/src
      - ./dist:/app/book-store
    container_name: book-store
    ports:
      - $PORT:3000
      - 9229:9229
    command: sh -c "npm run start"

networks:
  local:
